name: binary swap
source code: |-
  input: '1011'
  blank: ' '
  start state: q0
  table:
    # q0: read the first digit of a pair and remember it in the state
    q0:
      0: {R: qR0}
      1: {R: qR1}
      ' ': {R: qf}

    qR0:
      0: {write: 0, L: qW0}
      1: {write: 0, L: qW1}
      ' ': {L: qf}  
    qR1:
      0: {write: 1, L: qW0}
      1: {write: 1, L: qW1}
      ' ': {L: qf}
    qW0:
      [0,1]: {write: 0, R: qS}
    qW1:
      [0,1]: {write: 1, R: qS}
    # qS: step over the second digit to the next pair
    qS:
      [0,1]: {R: q0}
    # qf: final state (halt)
    qf:
positions:
  q0: {x: 529.02, y: 256.7}
  qR0: {x: 226.6, y: 252.09}
  qR1: {x: 780, y: 257.62}
  qW0: {x: 207.31, y: 20}
  qW1: {x: 780, y: 20}
  qS: {x: 523.48, y: 20}
  qf: {x: 543.75, y: 480}
editor contents: |-
  input: '1011' # тестовая строка для ввода
  blank: ' ' # пустой символ алфавита
  start state: q0  # стартовое состояние
  table:
    q0:
      0: {R: qR0}
      1: {R: qR1}
      ' ': {R: qf}

    qR0:
      0: {write: 0, L: qW0}
      1: {write: 0, L: qW1}
      ' ': {L: qf}  
    qR1:
      0: {write: 1, L: qW0}
      1: {write: 1, L: qW1}
      ' ': {L: qf}
    qW0:
      [0,1]: {write: 0, R: qS}
    qW1:
      [0,1]: {write: 1, R: qS}
    qS:
      [0,1]: {R: q0}
    qf:
